<?php

use Drupal\search_api\IndexInterface;

/**
 * Implements hook_form_alter().
 * @param $form
 * @param FormStateInterface $form_state
 * @param $form_id
 */
function asu_search_form_views_exposed_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id){
  if ($form['#id'] == 'views-exposed-form-solr-search-content-page-2') {
    $current_path = \Drupal::service('path.current')->getPath();
    $new_search_path = str_replace('/node/', '/search-collection/', $current_path);
    $form['#action'] = $new_search_path;
  }
}

/**
 * Implements hook_search_api_solr_field_mapping_alter().
 */
function asu_search_search_api_solr_field_mapping_alter(IndexInterface $index, array &$fields, string $language_id) {
  // Make file size and mime type multi-valued.
  $fields['field_file_size'] = 'itm_field_file_size';
  $fields['field_mime_type'] = 'sm_field_mime_type';
}
