_core:
  default_config_hash: 1ejRi9pxVG9uwI5vxxPE9KmzsUfOz3vh_tFabZgcLOQ
reference_field: field_as_reference
link_field: field_handle
paragraph_type: as_reference
ao_ref_id_field: field_as_ref_id
do_id_field: field_as_do_id
repo_id_field: field_as_repository_id
