definitions:
  contact__site_page:
    menu_name: footer
    parent: ''
    weight: 0
    expanded: false
    enabled: true
  standard__front_page:
    enabled: false
    menu_name: main
    parent: ''
    expanded: false
    weight: -50
  asu_search__search_menu:
    weight: -48
    menu_name: main
    parent: ''
    expanded: false
    enabled: true
