module:
  action: 0
  address: 0
  admin_toolbar: 0
  admin_toolbar_tools: 0
  archivesspace: 0
  archivesspace_extensions: 0
  asu_admin_toolbox: 0
  asu_brand: 0
  asu_breadcrumbs: 0
  asu_collection_extras: 0
  asu_custom_rdf: 0
  asu_default_fields: 0
  asu_deposit_methods: 0
  asu_derivatives: 0
  asu_header: 0
  asu_islandora_utils: 0
  asu_item_extras: 0
  asu_migrate: 0
  asu_mods: 0
  asu_permissions: 0
  asu_search: 0
  asu_searchable_entity_formatter: 0
  asu_statistics: 0
  asu_taxonomies: 0
  automated_cron: 0
  bagger_extension: 0
  basic_auth: 0
  big_pipe: 0
  block: 0
  block_content: 0
  breakpoint: 0
  ckeditor5: 0
  comment: 0
  config: 0
  config_filter: 0
  config_split: 0
  config_update: 0
  contact: 0
  content_browser: 0
  content_change_digest: 0
  content_moderation: 0
  context: 0
  context_ui: 0
  contextual: 0
  controlled_access_terms: 0
  controlled_access_terms_defaults: 0
  csv_serialization: 0
  ctools: 0
  datetime: 0
  dblog: 0
  deposit_agreement: 0
  diff: 0
  dynamic_page_cache: 0
  editor: 0
  embed: 0
  entity: 0
  entity_browser: 0
  entity_embed: 0
  entity_reference_revisions: 0
  entity_reference_unpublished: 0
  eva: 0
  externalauth: 0
  facets: 0
  facets_range_widget: 0
  facets_rest: 0
  facets_summary: 0
  features: 0
  features_ui: 0
  field: 0
  field_group: 0
  field_permissions: 0
  field_ui: 0
  file: 0
  file_replace: 0
  filehash: 0
  filter: 0
  flexible_permissions: 0
  flexslider: 0
  flexslider_fields: 0
  flexslider_views: 0
  flysystem: 0
  format_bytes: 0
  geolocation: 0
  gnode: 0
  google_analytics: 0
  group: 0
  hal: 0
  hdl: 0
  help: 0
  history: 0
  honeypot: 0
  image: 0
  image_captcha: 0
  inline_entity_form: 0
  islandora: 0
  islandora_audio: 0
  islandora_core_feature: 0
  islandora_fits: 0
  islandora_iiif: 0
  islandora_image: 0
  islandora_matomo: 0
  islandora_matomo_blocks: 0
  islandora_mirador: 0
  islandora_repository_reports: 0
  islandora_text_extraction: 0
  islandora_text_extraction_defaults: 0
  islandora_tokens: 0
  islandora_video: 0
  islandora_workbench_integration: 0
  jquery_ui: 0
  jquery_ui_autocomplete: 0
  jquery_ui_menu: 0
  jquery_ui_slider: 0
  jquery_ui_touch_punch: 0
  json_field: 0
  jsonapi: 0
  jsonld: 0
  jwt: 0
  jwt_auth_issuer: 0
  key: 0
  language: 0
  layout_builder: 0
  layout_discovery: 0
  link: 0
  masquerade: 0
  matomo: 0
  media: 0
  menu_ui: 0
  metatag: 0
  metatag_google_scholar: 0
  metatag_verification: 0
  migrate: 0
  migrate_devel: 0
  migrate_file: 0
  migrate_plus: 0
  migrate_source_csv: 0
  migrate_tools: 0
  mysql: 0
  node: 0
  openseadragon: 0
  options: 0
  page_cache: 0
  paragraphs_type_permissions: 0
  path: 0
  path_alias: 0
  pdf: 0
  persistent_identifiers: 0
  prepopulate: 0
  rdf: 0
  recaptcha_v3: 0
  redirect: 0
  redis: 0
  responsive_image: 0
  rest: 0
  rest_oai_pmh: 0
  restui: 0
  rrssb: 0
  s3fs_cors: 0
  schema_metatag: 0
  search_api: 0
  search_api_solr: 0
  serialization: 0
  shortcut: 0
  simple_sitemap: 0
  smtp: 0
  soft_delete: 0
  superfish: 0
  syslog: 0
  system: 0
  taxonomy: 0
  text: 0
  title_length: 0
  token: 0
  toolbar: 0
  tour: 0
  tracker: 0
  transliterate_filenames: 0
  twig_tweak: 0
  update: 0
  user: 0
  variationcache: 0
  views_bootstrap: 0
  views_bulk_edit: 0
  views_bulk_operations: 0
  views_data_export: 0
  views_ui: 0
  webform: 0
  webform_ui: 0
  workbench: 0
  workbench_email: 0
  workflows: 0
  menu_link_content: 1
  pathauto: 1
  content_translation: 10
  views: 10
  paragraphs: 11
  standard: 1000
theme:
  claro: 0
  asulib_barrio: 0
  bootstrap_barrio: 0
  bootstrap_sass: 0
profile: standard
