site_id: '3'
url_http: http://localhost:8080/matomo
url_https: http://localhost:8080/matomo
domain_mode: 0
visibility:
  request_path_mode: 0
  request_path_pages: "/admin\r\n/admin/*\r\n/batch\r\n/node/add*\r\n/node/*/*\r\n/user/*/*"
  user_role_mode: 1
  user_role_roles:
    administrator: administrator
  user_account_mode: 1
track:
  mailto: true
  files: true
  files_extensions: '7z|aac|arc|arj|asf|asx|avi|bin|csv|doc(x|m)?|dot(x|m)?|exe|flv|gif|gz|gzip|hqx|jar|jpe?g|js|mp(2|3|4|e?g)|mov(ie)?|msi|msp|pdf|phps|png|ppt(x|m)?|pot(x|m)?|pps(x|m)?|ppam|sld(x|m)?|thmx|qtm?|ra(m|r)?|sea|sit|tar|tgz|torrent|txt|wav|wma|wmv|wpd|xls(x|m|b)?|xlt(x|m)|xlam|xml|z|zip'
  colorbox: true
  userid: false
  messages: {  }
  site_search: false
privacy:
  donottrack: true
  disablecookies: false
custom:
  variable:
    1:
      slot: 1
      name: ''
      value: ''
      scope: visit
    2:
      slot: 2
      name: ''
      value: ''
      scope: visit
    3:
      slot: 3
      name: ''
      value: ''
      scope: visit
    4:
      slot: 4
      name: ''
      value: ''
      scope: visit
    5:
      slot: 5
      name: ''
      value: ''
      scope: visit
codesnippet:
  before: ''
  after: ''
translation_set: false
cache: false
page_title_hierarchy: false
page_title_hierarchy_exclude_home: true
disable_tracking: false
status_codes_disabled: {  }
