archivesspace_extentions.settings:
  type: config_object
  label: 'ArchivesSpace Extentions'
  mapping:
    reference_field:
      type: string
      label: 'ArchivesSpace Reference Field'
    ao_ref_id_field:
      type: string
      label: 'Archival Object Field'
    repo_id_field:
      type: string
      label: 'Repository Identifier Field'
    do_ref_id_field:
      type: string
      label: 'Digital Object Field'
