<?php

/**
 * @file
 * Contains asu_deposit_methods.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\asu_deposit_methods\Form\SheetMusicChild;

/**
 * Implements hook_help().
 */
function asu_deposit_methods_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the asu_deposit_methods module.
    case 'help.page.asu_deposit_methods':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Custom deposit methods for ASU repositories') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_entity_type_build().
 */
function asu_deposit_methods_entity_type_build(array &$entity_types) {
  $entity_types['node']->setFormClass('sheet_music', 'Drupal\node\NodeForm');
  $entity_types['node']->setFormClass('sheet_music_child', 'Drupal\node\NodeForm');
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function asu_deposit_methods_form_node_asu_repository_item_sheet_music_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $config = \Drupal::config('asu_deposit_methods.depositsettings');

  if ($config->get('sheet_music_default_genre')) {
    $default_genre = \Drupal::entityTypeManager()->getStorage('taxonomy_term')->load($config->get('sheet_music_default_genre'));
    $form['field_genre']['widget'][0]['target_id']['#default_value'] = $default_genre;
  }

  if ($config->get('sheet_music_default_copyright')) {
    $form['field_copyright_statement']['widget']['#default_value'] = $config->get('sheet_music_default_copyright');
  }

  if ($config->get('sheet_music_default_reuse')) {
    $form['field_reuse_permissions']['widget']['#default_value'] = $config->get('sheet_music_default_reuse');
  }

  if ($config->get('sheet_music_default_model')) {
    $form['field_model']['widget']['#default_value'] = $config->get('sheet_music_default_model');
  }

  if ($config->get('sheet_music_default_identifier_type')) {
    $form['field_typed_identifier']['widget'][0]['subform']['field_identifier_type']['widget']['#default_value'] = $config->get('sheet_music_default_identifier_type');
  }

  if ($config->get('sheet_music_default_collection')) {
    $default_collection = \Drupal::entityTypeManager()->getStorage('node')->load($config->get('sheet_music_default_collection'));
    $form['field_member_of']['widget'][0]['target_id']['#default_value'] = $default_collection;
    $of_perms = $default_collection->get('field_default_original_file_perm')->entity;
    $sf_perms = $default_collection->get('field_default_derivative_file_pe')->entity;
    $form['field_default_derivative_file_pe']['widget'][0]['target_id']['#default_value'] = $sf_perms;
    $form['field_default_original_file_perm']['widget'][0]['target_id']['#default_value'] = $of_perms;
  }

  $form['moderation_state']['widget'][0]['state']['#default_value'] = 'published';
  $form['actions']['submit']['#submit'][] = 'asu_deposit_methods_sheet_music_parent_submit';
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function asu_deposit_methods_form_node_asu_repository_item_sheet_music_child_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  SheetMusicChild::alter($form, $form_state);
}

/**
 * Submit handling for sheet music parent.
 */
function asu_deposit_methods_sheet_music_parent_submit(array &$form, FormStateInterface $form_state) {
  \Drupal::messenger()->addMessage(t('Sheet Music item created. Add child items now.'));
  $node_id = $form_state->getValue('nid');
  if ($node_id) {
    $form_state->setRedirect('asu_deposit_methods.sheet_music.add_child', [
      'node_type' => 'asu_repository_item',
      'parent' => $node_id,
    ]);
  }
}
