riprap_mode: remote
riprap_rest_endpoint: 'http://35.163.226.190/api/fixity'
riprap_local_directory: /path/to/riprap
riprap_local_settings_file: /path/to/riprap/settings.yml
execute_riprap_in_cron: 0
number_of_events: '10'
gemini_rest_endpoint: 'http://34.222.121.97/gemini'
use_drupal_urls: 0
log_riprap_warnings: 1
use_sample_failed_fixity_events: 0
fixity_terms: '16'
fixity_content_type: islandora_object
user_name: admin
user_pass: repo1Repo2repo3
show_riprap_warnings: 0
