<?php

namespace Drupal\asu_migrate\Plugin\migrate\process;

use Drupal\migrate\ProcessPluginBase;
use Drupal\migrate\MigrateExecutableInterface;
use Drupal\migrate\MigrateSkipProcessException;
use Drupal\migrate\Row;
use Drupal\taxonomy\Entity\Term;

/**
 * Check if term exists and create new if doesn't.
 *
 * @MigrateProcessPlugin(
 *   id = "typed_relation_generate"
 * )
 */
class TypedRelationGenerate extends NameURIGenerate {
  protected $relator_map = [
    "relators:abr" => strtolower("Abridger"),
    "relators:act" => strtolower("Actor"),
    "relators:adp" => strtolower("Adapter"),
    "relators:rcp" => strtolower("Addressee"),
    "relators:anl" => strtolower("Analyst"),
    "relators:anm" => strtolower("Animator"),
    "relators:ann" => strtolower("Annotator"),
    "relators:apl" => strtolower("Appellant"),
    "relators:ape" => strtolower("Appellee"),
    "relators:app" => strtolower("Applicant"),
    "relators:arc" => strtolower("Architect"),
    "relators:arr" => strtolower("Arranger"),
    "relators:acp" => strtolower("Art copyist"),
    "relators:adi" => strtolower("Art director"),
    "relators:art" => strtolower("Artist"),
    "relators:ard" => strtolower("Artistic director"),
    "relators:asg" => strtolower("Assignee"),
    "relators:asn" => strtolower("Associated name"),
    "relators:att" => strtolower("Attributed name"),
    "relators:auc" => strtolower("Auctioneer"),
    "relators:aut" => strtolower("Author"),
    "relators:aqt" => strtolower("Author in quotations or text abstracts"),
    "relators:aft" => strtolower("Author of afterword, colophon, etc."),
    "relators:aud" => strtolower("Author of dialog"),
    "relators:aui" => strtolower("Author of introduction, etc."),
    "relators:ato" => strtolower("Autographer"),
    "relators:ant" => strtolower("Bibliographic antecedent"),
    "relators:bnd" => strtolower("Binder"),
    "relators:bdd" => strtolower("Binding designer"),
    "relators:blw" => strtolower("Blurb writer"),
    "relators:bkd" => strtolower("Book designer"),
    "relators:bkp" => strtolower("Book producer"),
    "relators:bjd" => strtolower("Bookjacket designer"),
    "relators:bpd" => strtolower("Bookplate designer"),
    "relators:bsl" => strtolower("Bookseller"),
    "relators:brl" => strtolower("Braille embosser"),
    "relators:brd" => strtolower("Broadcaster"),
    "relators:cll" => strtolower("Calligrapher"),
    "relators:ctg" => strtolower("Cartographer"),
    "relators:cas" => strtolower("Caster"),
    "relators:cns" => strtolower("Censor"),
    "relators:chr" => strtolower("Choreographer"),
    "relators:clb" => strtolower("Collaborator"),
    "relators:cng" => strtolower("Cinematographer"),
    "relators:cli" => strtolower("Client"),
    "relators:cor" => strtolower("Collection registrar"),
    "relators:col" => strtolower("Collector"),
    "relators:clt" => strtolower("Collotyper"),
    "relators:clr" => strtolower("Colorist"),
    "relators:cmm" => strtolower("Commentator"),
    "relators:cwt" => strtolower("Commentator for written text"),
    "relators:com" => strtolower("Compiler"),
    "relators:cpl" => strtolower("Complainant"),
    "relators:cpt" => strtolower("Complainant-appellant"),
    "relators:cpe" => strtolower("Complainant-appellee"),
    "relators:cmp" => strtolower("Composer"),
    "relators:cmt" => strtolower("Compositor"),
    "relators:ccp" => strtolower("Conceptor"),
    "relators:cnd" => strtolower("Conductor"),
    "relators:con" => strtolower("Conservator"),
    "relators:csl" => strtolower("Consultant"),
    "relators:csp" => strtolower("Consultant to a project"),
    "relators:cos" => strtolower("Contestant"),
    "relators:cot" => strtolower("Contestant-appellant"),
    "relators:coe" => strtolower("Contestant-appellee"),
    "relators:cts" => strtolower("Contestee"),
    "relators:ctt" => strtolower("Contestee-appellant"),
    "relators:cte" => strtolower("Contestee-appellee"),
    "relators:ctr" => strtolower("Contractor"),
    "relators:ctb" => strtolower("Contributor"),
    "relators:cpc" => strtolower("Copyright claimant"),
    "relators:cph" => strtolower("Copyright holder"),
    "relators:crr" => strtolower("Corrector"),
    "relators:crp" => strtolower("Correspondent"),
    "relators:cst" => strtolower("Costume designer"),
    "relators:cou" => strtolower("Court governed"),
    "relators:crt" => strtolower("Court reporter"),
    "relators:cov" => strtolower("Cover designer"),
    "relators:cre" => strtolower("Creator"),
    "relators:cur" => strtolower("Curator"),
    "relators:dnc" => strtolower("Dancer"),
    "relators:dtc" => strtolower("Data contributor"),
    "relators:dtm" => strtolower("Data manager"),
    "relators:dte" => strtolower("Dedicatee"),
    "relators:dto" => strtolower("Dedicator"),
    "relators:dfd" => strtolower("Defendant"),
    "relators:dft" => strtolower("Defendant-appellant"),
    "relators:dfe" => strtolower("Defendant-appellee"),
    "relators:dgc" => strtolower("Degree Committee Member"),
    "relators:dgc" => strtolower("Committee Member"),
    "relators:dgg" => strtolower("Degree granting institution"),
    "relators:dgs" => strtolower("Degree supervisor"),
    "relators:dln" => strtolower("Delineator"),
    "relators:dpc" => strtolower("Depicted"),
    "relators:dpt" => strtolower("Depositor"),
    "relators:dsr" => strtolower("Designer"),
    "relators:drt" => strtolower("Director"),
    "relators:dis" => strtolower("Dissertant"),
    "relators:dbp" => strtolower("Distribution place"),
    "relators:dst" => strtolower("Distributor"),
    "relators:dnr" => strtolower("Donor"),
    "relators:drm" => strtolower("Draftsman"),
    "relators:dub" => strtolower("Dubious author"),
    "relators:edt" => strtolower("Editor"),
    "relators:edc" => strtolower("Editor of compilation"),
    "relators:edm" => strtolower("Editor of moving image work"),
    "relators:elg" => strtolower("Electrician"),
    "relators:elt" => strtolower("Electrotyper"),
    "relators:enj" => strtolower("Enacting jurisdiction"),
    "relators:eng" => strtolower("Engineer"),
    "relators:egr" => strtolower("Engraver"),
    "relators:etr" => strtolower("Etcher"),
    "relators:evp" => strtolower("Event place"),
    "relators:exp" => strtolower("Expert"),
    "relators:fac" => strtolower("Facsimilist"),
    "relators:fld" => strtolower("Field director"),
    "relators:fmd" => strtolower("Film director"),
    "relators:fds" => strtolower("Film distributor"),
    "relators:flm" => strtolower("Film editor"),
    "relators:fmp" => strtolower("Film producer"),
    "relators:fmk" => strtolower("Filmmaker"),
    "relators:fpy" => strtolower("First party"),
    "relators:frg" => strtolower("Forger"),
    "relators:fmo" => strtolower("Former owner"),
    "relators:fnd" => strtolower("Funder"),
    "relators:gis" => strtolower("Geographic information specialist"),
    "relators:grt" => strtolower("Graphic technician"),
    "relators:hnr" => strtolower("Honoree"),
    "relators:hst" => strtolower("Host"),
    "relators:his" => strtolower("Host institution"),
    "relators:ilu" => strtolower("Illuminator"),
    "relators:ill" => strtolower("Illustrator"),
    "relators:ins" => strtolower("Inscriber"),
    "relators:itr" => strtolower("Instrumentalist"),
    "relators:ive" => strtolower("Interviewee"),
    "relators:ivr" => strtolower("Interviewer"),
    "relators:inv" => strtolower("Inventor"),
    "relators:isb" => strtolower("Issuing body"),
    "relators:jud" => strtolower("Judge"),
    "relators:jug" => strtolower("Jurisdiction governed"),
    "relators:lbr" => strtolower("Laboratory"),
    "relators:ldr" => strtolower("Laboratory director"),
    "relators:lsa" => strtolower("Landscape architect"),
    "relators:led" => strtolower("Lead"),
    "relators:len" => strtolower("Lender"),
    "relators:lil" => strtolower("Libelant"),
    "relators:lit" => strtolower("Libelant-appellant"),
    "relators:lie" => strtolower("Libelant-appellee"),
    "relators:lel" => strtolower("Libelee"),
    "relators:let" => strtolower("Libelee-appellant"),
    "relators:lee" => strtolower("Libelee-appellee"),
    "relators:lbt" => strtolower("Librettist"),
    "relators:lse" => strtolower("Licensee"),
    "relators:lso" => strtolower("Licensor"),
    "relators:lgd" => strtolower("Lighting designer"),
    "relators:ltg" => strtolower("Lithographer"),
    "relators:lyr" => strtolower("Lyricist"),
    "relators:mfp" => strtolower("Manufacture place"),
    "relators:mfr" => strtolower("Manufacturer"),
    "relators:mrb" => strtolower("Marbler"),
    "relators:mrk" => strtolower("Markup editor"),
    "relators:med" => strtolower("Medium"),
    "relators:mdc" => strtolower("Metadata contact"),
    "relators:mte" => strtolower("Metal-engraver"),
    "relators:mtk" => strtolower("Minute taker"),
    "relators:mod" => strtolower("Moderator"),
    "relators:mon" => strtolower("Monitor"),
    "relators:mcp" => strtolower("Music copyist"),
    "relators:msd" => strtolower("Musical director"),
    "relators:mus" => strtolower("Musician"),
    "relators:nrt" => strtolower("Narrator"),
    "relators:osp" => strtolower("Onscreen presenter"),
    "relators:opn" => strtolower("Opponent"),
    "relators:orm" => strtolower("Organizer"),
    "relators:org" => strtolower("Originator"),
    "relators:oth" => strtolower("Other"),
    "relators:own" => strtolower("Owner"),
    "relators:pan" => strtolower("Panelist"),
    "relators:ppm" => strtolower("Papermaker"),
    "relators:pta" => strtolower("Patent applicant"),
    "relators:pth" => strtolower("Patent holder"),
    "relators:pat" => strtolower("Patron"),
    "relators:prf" => strtolower("Performer"),
    "relators:pma" => strtolower("Permitting agency"),
    "relators:pht" => strtolower("Photographer"),
    "relators:ptf" => strtolower("Plaintiff"),
    "relators:ptt" => strtolower("Plaintiff-appellant"),
    "relators:pte" => strtolower("Plaintiff-appellee"),
    "relators:plt" => strtolower("Platemaker"),
    "relators:pra" => strtolower("Praeses"),
    "relators:pre" => strtolower("Presenter"),
    "relators:prt" => strtolower("Printer"),
    "relators:pop" => strtolower("Printer of plates"),
    "relators:prm" => strtolower("Printmaker"),
    "relators:prc" => strtolower("Process contact"),
    "relators:pro" => strtolower("Producer"),
    "relators:prn" => strtolower("Production company"),
    "relators:prs" => strtolower("Production designer"),
    "relators:pmn" => strtolower("Production manager"),
    "relators:prd" => strtolower("Production personnel"),
    "relators:prp" => strtolower("Production place"),
    "relators:prg" => strtolower("Programmer"),
    "relators:pdr" => strtolower("Project director"),
    "relators:pfr" => strtolower("Proofreader"),
    "relators:prv" => strtolower("Provider"),
    "relators:pup" => strtolower("Publication place"),
    "relators:pbl" => strtolower("Publisher"),
    "relators:pbd" => strtolower("Publishing director"),
    "relators:ppt" => strtolower("Puppeteer"),
    "relators:rdd" => strtolower("Radio director"),
    "relators:rpc" => strtolower("Radio producer"),
    "relators:rce" => strtolower("Recording engineer"),
    "relators:rcd" => strtolower("Recordist"),
    "relators:red" => strtolower("Redaktor"),
    "relators:ren" => strtolower("Renderer"),
    "relators:rpt" => strtolower("Reporter"),
    "relators:rps" => strtolower("Repository"),
    "relators:rth" => strtolower("Research team head"),
    "relators:rtm" => strtolower("Research team member"),
    "relators:res" => strtolower("Researcher"),
    "relators:rsp" => strtolower("Respondent"),
    "relators:rst" => strtolower("Respondent-appellant"),
    "relators:rse" => strtolower("Respondent-appellee"),
    "relators:rpy" => strtolower("Responsible party"),
    "relators:rsg" => strtolower("Restager"),
    "relators:rsr" => strtolower("Restorationist"),
    "relators:rev" => strtolower("Reviewer"),
    "relators:rbr" => strtolower("Rubricator"),
    "relators:sce" => strtolower("Scenarist"),
    "relators:sad" => strtolower("Scientific advisor"),
    "relators:aus" => strtolower("Screenwriter"),
    "relators:scr" => strtolower("Scribe"),
    "relators:scl" => strtolower("Sculptor"),
    "relators:spy" => strtolower("Second party"),
    "relators:sec" => strtolower("Secretary"),
    "relators:sll" => strtolower("Seller"),
    "relators:std" => strtolower("Set designer"),
    "relators:stg" => strtolower("Setting"),
    "relators:sgn" => strtolower("Signer"),
    "relators:sng" => strtolower("Singer"),
    "relators:sds" => strtolower("Sound designer"),
    "relators:spk" => strtolower("Speaker"),
    "relators:spn" => strtolower("Sponsor"),
    "relators:sgd" => strtolower("Stage director"),
    "relators:stm" => strtolower("Stage manager"),
    "relators:stn" => strtolower("Standards body"),
    "relators:str" => strtolower("Stereotyper"),
    "relators:stl" => strtolower("Storyteller"),
    "relators:sht" => strtolower("Supporting host"),
    "relators:srv" => strtolower("Surveyor"),
    "relators:tch" => strtolower("Teacher"),
    "relators:tcd" => strtolower("Technical director"),
    "relators:tld" => strtolower("Television director"),
    "relators:tlp" => strtolower("Television producer"),
    "relators:ths" => strtolower("Thesis advisor"),
    "relators:ths" => strtolower("Thesis director"),
    "relators:trc" => strtolower("Transcriber"),
    "relators:trl" => strtolower("Translator"),
    "relators:tyd" => strtolower("Type designer"),
    "relators:tyg" => strtolower("Typographer"),
    "relators:uvp" => strtolower("University place"),
    "relators:vdg" => strtolower("Videographer"),
    "relators:voc" => strtolower("Vocalist"),
    "relators:vac" => strtolower("Voice actor"),
    "relators:wit" => strtolower("Witness"),
    "relators:wde" => strtolower("Wood engraver"),
    "relators:wdc" => strtolower("Woodcutter"),
    "relators:wam" => strtolower("Writer of accompanying material"),
    "relators:wac" => strtolower("Writer of added commentary"),
    "relators:wal" => strtolower("Writer of added lyrics"),
    "relators:wat" => strtolower("Writer of added text"),
    "relators:win" => strtolower("Writer of introduction"),
    "relators:wpr" => strtolower("Writer of preface"),
    "relators:wst" => strtolower("Writer of supplementary textual content")
  ];

  /**
   * {@inheritdoc}
   */
  public function transform($value, MigrateExecutableInterface $migrate_executable, Row $row, $destination_property) {
    if (is_array($value)) {
      $name = $value['name'];
      $uri = (array_key_exists('uri', $value) ? $value['uri'] : '');
      $relator = (array_key_exists('rel', $value) ?
        (strstr($value['rel'], 'relators:') ? $value['rel'] : 'relators:' . $value['rel']) : '');
      unset($value['rel']);
    }
    else {
      if (array_key_exists('relator', $this->configuration)) {
        $relator = $this->configuration['relator'];
      }
      else {
        $parts = explode($this->configuration['delimiter'], $value);
        $relator_string = array_pop($parts);
        $relator = $this->look_up_relator($relator_string);
        $value = implode($this->configuration['delimiter'], $parts);
      }
    }
    $term = parent::transform($value, $migrate_executable, $row, $destination_property);
    $typed_relation = [
      'rel_type' => $relator,
      'target_id' => $term
    ];
    return $typed_relation;
  }

  public function look_up_relator(string $relator) {
    return array_search(strtolower($relator), $this->relator_map);
  }

}
