field.formatter.settings.typed_relation_brief:
  type: mapping
  label: 'Typed Relation Brief settings'
  mapping:
    unlinked_without_uri:
      type: boolean
      label: 'Unlink Relations w/o a URI'
