<?php

/**
 * @file
 * Contains asu_permissions.module.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\group\Entity\Group;

/**
 * Implements hook_entity_insert().
 *
 * Alternatively could trigger this with a context reaction.
 */
function asu_permissions_entity_insert(EntityInterface $entity) {
  $ettype = $entity->getEntityTypeId();
  if ($ettype == "node") {
    \Drupal::logger('asu_permissions')->info("its a node");
    \Drupal::logger('asu_permissions')->info("bundle is " . $entity->bundle());
    if ($entity->bundle() == "collection") {
      // create a new group for the collection
      $pluginId = 'group_node:' . $entity->bundle();
      $col_group = Group::create(['type' => 'collection_group', 'label' => 'Collection ' . $entity->id() . ' Group']);
      $col_group->save();
      $col_group->addContent($entity, $pluginId);
      $col_group->save();
    } elseif ($entity->bundle() == 'asu_repository_item'){
      // add the asu_repository_item to the parent collection's group
      // TODO - will this need to traverse up the member_of tree to a grandparent?
      $parents = $entity->field_member_of->getValue();
      $pluginId = 'group_node:' . $entity->bundle();
      foreach ($parents as $parent) {
        $cid = $parent['target_id'];
        $database = \Drupal::database();
        $query = $database->select('groups_field_data', 'gfd');
        $query->condition('gfd.label', 'Collection ' . $cid . ' Group', '=')
              ->fields('gfd', ['id'])
              ->range(0, 1);
        $result = $query->execute();
        foreach($result as $record){
          $col_group = Group::load($record->id);
          $col_group->addContent($entity, $pluginId);
        }
      }
    }
  }
}

/**
 * Implements hook_node_view().
 *
 * Could also be done in the template.
 */
function asu_permissions_node_view(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display, $view_mode) {
  if ($entity->bundle() == "collection" || $entity->bundle() == "islandora_object") {
    $build['developer_addition_markup'] = array(
      '#markup' => '<a target="_blank" href="/form/feedback?source_entity_type=node&source_entity_id=' . $entity->id() . '&item=' . $entity->id() . '">Feedback</a>',
      '#prefix' => '<div class="feedback-buttons">',
      '#suffix' => '</div>'
    );
  }
}
