<?php

/**
 * @file
 * Contains asu_brand.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function asu_brand_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the asu_brand module.
    case 'help.page.asu_brand':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Provides ASU header and footer blocks without the use of an ASU based theme.') . '</p>';
      return $output;

    default:
  }
}

