<?php

/**
 * @file
 * Contains asu_brand.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Header default version
 */
const ASU_BRAND_HEADER_VERSION_DEFAULT = 'stable';

/**
 * URL Basepath
 */
const ASU_BRAND_HEADER_BASEPATH_DEFAULT = 'http://www.asu.edu/asuthemes';

/**
 * Default template name
 */
const ASU_BRAND_HEADER_TEMPLATE_DEFAULT = 'default';

/**
 * Default cache lifetime is 48 Hours ( 60 x 60 x 48 )
 */
const ASU_BRAND_CACHE_LIFETIME = '172800';

/**
 * Default machine name of site menu to inject into the responsive header menu
 */
const ASU_BRAND_SITE_MENU_NAME_DEFAULT = 'main';

/**
 * Google Tag Manager ID
 */
const ASU_BRAND_GTM_ID = 'GTM-KDWN8Z';

/**
 * Implements hook_help().
 */
function asu_brand_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the asu_brand module.
    case 'help.page.asu_brand':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Provides ASU header and footer blocks without the use of an ASU based theme.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_page_top().
 */
function asu_brand_page_top(&$page) {
  $content = '';

  $current_theme = \Drupal::service('theme.manager')->getActiveTheme();

  $blocks = \Drupal::entityTypeManager()
    ->getStorage('block')
    ->loadByProperties(['plugin' => 'asu_brand_header', 'theme' => $current_theme->getName()]);

  foreach ($blocks as $id=>$block) {

    $settings = $block->get('settings');

    // Add noscript snippets to page_top region.
    if ($settings['asu_gtm']) {
      $content .= '<noscript><iframe src="//www.googletagmanager.com/ns.html?id=' . ASU_BRAND_GTM_ID .
        '"height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>';
    }

    if ($settings['custom_gtm']) {
      $custom_gtm_id = $settings['custom_gtm_id'];
      $content .= '<noscript><iframe src="//www.googletagmanager.com/ns.html?id=' . $custom_gtm_id .
        '"height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>';
    }

  }

  // Render iframe as close to the opening body tag as possible.
  if ($content) {
    $page['asu_brand_gtm_code'] = [
      '#type' => 'inline_template',
      '#template' => '{{ html | raw }}',
      '#context' => [
        'html' => $content
      ],
      '#weight' => -100,
    ];
  }
}
