<?php

/**
 * @file
 * Contains self_deposit.module.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\user\UserInterface;
use Drupal\self_deposit\Form\FieldModelToMedia;
use Drupal\self_deposit\Form\NodeMediaRedirect;

/**
 * Implements hook_help().
 */
function self_deposit_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the self_deposit module.
    case 'help.page.self_deposit':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('A module to facilitate self deposit') . '</p>';
      return $output;

    default:
  }
}
