<?php

/**
 * Implements hook_form_alter().
 */
function asu_self_deposit_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  if ($form_id == 'node_asu_repository_item_self_submit_form') {
    foreach (array_keys($form['actions']) as $action) {
      if ($action != 'preview' && isset($form['actions'][$action]['#type']) && $form['actions'][$action]['#type'] === 'submit') {
        $form['actions'][$action]['#submit'] = ['asu_self_submit_save_node_handler'];
      }
    }
  }
}

function asu_self_deposit_save_node_handler(&$form, Drupal\Core\Form\FormState $form_state) {
  $messenger = \Drupal::messenger();
  // Should this redirect anywhere specific?
  $message = t('Save Node handler for node "@node_title".',
    array(
      '@node_title' => $node_title,
  ));
  \Drupal::logger('Self Deposit')->info($message);
  $messenger->addMessage($message, $messenger::TYPE_STATUS);
  // @todo need to redirect to the media page
  $form_state->setRedirect('entity.node.canonical', ['node' => $entity->id()]);
}
